# Generated by Django 3.2.5 on 2021-07-18 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VotesCounter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('votes', models.IntegerField(default=0, verbose_name='Votes')),
                ('answer_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='polls.answer', verbose_name='Answer')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.question', verbose_name='Question')),
            ],
        ),
        migrations.AlterField(
            model_name='voter',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.votescounter', verbose_name='Answer'),
        ),
        migrations.DeleteModel(
            name='VoteCounter',
        ),
    ]
