# Generated by Django 3.2.5 on 2021-07-20 00:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='description',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='votescounter',
            old_name='answer_id',
            new_name='answer',
        ),
        migrations.RenameField(
            model_name='votescounter',
            old_name='question_id',
            new_name='question',
        ),
    ]
