# Generated by Django 3.2.5 on 2021-07-20 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210719_2018'),
    ]

    operations = [
        migrations.AlterField(
            model_name='votescounter',
            name='answer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.answer', verbose_name='Answer'),
        ),
    ]
