# Generated by Django 3.2.5 on 2021-07-21 17:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_question_answers'),
    ]

    operations = [
        migrations.AddField(
            model_name='description',
            name='date_published',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
