# Generated by Django 3.2.5 on 2021-07-16 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_max_votes_answer_question_result'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
    ]
