# Generated by Django 3.2.5 on 2021-07-16 02:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20210715_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='date_published',
            field=models.DateField(default=datetime.datetime(2021, 7, 15, 22, 10, 43, 935928)),
        ),
        migrations.AlterField(
            model_name='record',
            name='date',
            field=models.DateField(),
        ),
    ]
